export const PROPERTIES = {
    empresa: 'Mi Tienda',
    inicio: 'Iniciar Sesión',
    cerrar: 'Cerrar Sesión',
    bienvenida: 'Bienvenido',
    usuarioRequerido: 'Por favor ingrese su usuario',
    passwordRequerido: 'Por favor ingrese su contraseña',
    usuarioLogin: 'Usuario',
    passwordLogin: 'Contraseña',
    menuusuario: 'Usuario',
    tituloUsuario: 'Usuarios',
    buttonUsuario: 'Crear Usuario',
    mensajeAccion: 'Presione "Enter" para confirmar búsqueda',
    verUsuario: 'Ver',
    tituloNuevoUsuario: 'Alta de Usuario',
    tituloNuevoRol: 'Alta de Rol',
    tituloVerUsuario: 'Datos del Usuario',
    tituloVerRol: 'Datos del Rol',
    nombreCompleto: 'Nombre',
    apellidoCompleto: 'Apellido',
    direccion: 'Dirección',
    cedula: 'Cédula de identidad',
    telefono: 'Número de telefono',
    email: 'Email',
    guardar: 'Guardar',
    alerta: 'Debe completar todos los campos',
    roles: 'Roles y permisos',
    selecciona: 'Seleccioná un rol',
    rolSelecciona: 'Permisos del rol ',
    editar: 'Editar',
    bloqueo: 'ESTADO USUARIO',
    menuroles: 'Roles',
    buttonRol: 'Crear Rol',
    descripcion: 'Descripcion',
    titulo: 'Titulo',
    tituloPass: 'Gestionar contraseña',
    nuevoPass: 'Nueva contraseña:',
    repetirPass: 'Repetir contraseña:',
    errorPass: 'Las contraseñas no coinciden'
}
